/* Interface strings, in Spanish and English.
   Each entry is a string, a function (for plurals and placeholders) or an
   object of labels. They may contain HTML: they are ours, they don't come
   from outside. The functions use plu(), which lives in app.js.
   build.js refuses to build the app if one language is missing a key the
   other has, or if the code asks for one that doesn't exist. */
const STRINGS = {

es: {
  /* format */
  'locale': 'es-ES',
  'cm.lang': 'es',
  'date': (y, m, d) => d + '/' + m + '/' + y,
  'file.base': 'coleccion-pokemon',
  'csv.head': ['ID','Nombre','Expansion','Numero','Rareza','Variante','Estado','Idioma','Graduacion','Cantidad','PrecioUnidad_EUR','ValorTotal_EUR','PrecioCompra_EUR','Fuente','Actualizado','Notas'],
  'csv.sep': ';',
  'csv.dec': ',',
  'ui.lang': 'Idioma de la interfaz',

  /* header and tabs */
  'app.title': 'Mi Colección Pokémon TCG',
  'hdr.cards': 'cartas',
  'hdr.value': 'valor est.',
  'upd.btn': '⟳ Actualizar precios',
  'tab.col': '📚 Mi colección',
  'tab.search': '🔍 Buscar y añadir',
  'tab.sets': '🗂️ Explorar expansiones',
  'tab.wish': '⭐ Lista de deseos',
  'tab.stats': '📊 Estadísticas',
  'tab.settings': '⚙️ Ajustes',

  /* catalog, variant, price reference and table labels */
  'cats': { es: 'Español', en: 'English', ja: '日本語 (japonés)' },
  'vars': { normal: 'Normal', holo: 'Holo', reverse: 'Reverse Holo', '1st': '1ª Edición', promo: 'Promo' },
  'modes': { trend: 'Tendencia', avg: 'Media de venta', avg30: 'Media 30 días', avg7: 'Media 7 días', low: 'Más bajo' },
  'th': { card: 'Carta', set: 'Expansión', num: 'Nº', rarity: 'Rareza', variant: 'Var.', cond: 'Est.', lang: 'Idi.',
          qty: 'Cant.', unit: 'Ud.', total: 'Total', paid: 'Compra', src: 'Fuente' },
  'lang.other': 'Otro',

  /* shared bits */
  'all.f': 'Todas',
  'all.m': 'Todos',
  'clear': 'Limpiar',
  'add': 'Añadir',
  'add.btn': '+ Añadir',
  'cancel': 'Cancelar',
  'save': 'Guardar',
  'retry': 'Reintentar',
  'optional': 'opcional',
  'f.set': 'Expansión',
  'f.rarity': 'Rareza',
  'f.variant': 'Variante',
  'f.lang': 'Idioma',
  'f.price': 'Precio',
  'f.catalog': 'Catálogo',
  'f.sort': 'Ordenar por',
  'f.qty': 'Cantidad',
  'f.cond': 'Estado',
  'f.number': 'Número',
  'f.notes': 'Notas',
  'no.price': 'sin precio',
  'unit': '/ud',
  'total': 'total',
  'num.short': 'Nº',
  'manual.short': 'a mano',
  'manual.set': 'Añadidas a mano',
  'n.cards': n => plu(n, 'carta', 'cartas'),
  'n.entries': n => plu(n, 'entrada', 'entradas'),
  'n.sets': n => plu(n, 'expansión', 'expansiones'),
  'ago.now': 'ahora mismo',
  'ago.min': n => 'hace ' + plu(n, 'minuto', 'minutos'),
  'ago.h': n => 'hace ' + plu(n, 'hora', 'horas'),
  'ago.d': n => 'hace ' + plu(n, 'día', 'días'),
  'tile.invested': 'Invertido',
  'tile.gain': 'Ganancia / pérdida',

  /* network and storage errors */
  'err.full': 'No se pudo guardar: almacenamiento lleno. Exporta una copia.',
  'err.429': 'Demasiadas consultas seguidas. Espera un minuto.',
  'err.busy': s => 'El servidor está ocupado (' + s + ')',
  'err.http': s => 'Error ' + s,
  'err.offline': 'Sin conexión',

  /* my collection */
  'col.search': 'Buscar en mi colección',
  'col.search.ph': 'Nombre, set, número, nota...',
  'col.allSets': 'Todas las expansiones',
  'price.none': '⚠ Sin precio',
  'price.mine': 'Precio puesto por mí',
  'price.auto': 'Precio automático',
  'sort.valueDesc': 'Valor total ↓',
  'sort.valueAsc': 'Valor total ↑',
  'sort.unitDesc': 'Precio unidad ↓',
  'sort.name': 'Nombre A-Z',
  'sort.set': 'Set y número',
  'sort.added': 'Añadidas recientes',
  'sort.qty': 'Cantidad ↓',
  'view.table': '📋 Ver como tabla',
  'view.grid': '🖼️ Ver como cuadrícula',
  'col.t.cards': 'Cartas en total',
  'col.t.distinct': n => plu(n, 'entrada distinta', 'entradas distintas'),
  'col.t.value': 'Valor estimado',
  'col.t.ref': m => 'Referencia: ' + m + ' de Cardmarket',
  'col.t.bought': 'Precio de compra anotado',
  'col.t.noBuy': 'Anota lo que pagaste al añadir',
  'col.t.top': 'Carta más cara',
  'col.t.unit': 'Precio por unidad',
  'col.t.cm': 'Precios de Cardmarket',
  'col.t.never': 'nunca',
  'col.t.checked': ago => 'Comprobado ' + ago,
  'col.t.press': 'Pulsa «Actualizar precios»',
  'col.t.oldest': d => ' · los más viejos, del ' + d,
  'col.empty': '<b>Tu colección está vacía.</b><br>Ve a <b>Buscar y añadir</b> o a <b>Explorar expansiones</b> para registrar tus primeras cartas.',
  'col.noMatch': 'Ningún resultado con esos filtros.',
  'col.showing': (n, total) => 'Mostrando ' + n + ' de ' + plu(total, 'entrada', 'entradas'),
  'col.cmTitle': 'Ver esta carta en Cardmarket',
  'col.notFound': 'No encuentro esa carta. Recarga la página.',
  'col.notFoundRetry': 'No encuentro esa carta. Recarga la página y vuelve a intentarlo.',
  'col.confirmDel': (name, where) => '¿Quitar «' + name + '» (' + where + ') de tu colección?',
  'col.deleted': 'Carta eliminada',
  'col.delFail': 'No se pudo eliminar',

  /* search and add */
  'search.title': 'Buscar cartas',
  'search.sub': 'Busca en el catálogo y añade las cartas a tu colección con un clic.',
  'search.name': 'Nombre de la carta',
  'search.name.ph': 'Ej: Charizard, Pikachu, Mew ex...',
  'search.setOpt': 'Expansión (opcional)',
  'search.num': 'Nº (opcional)',
  'search.num.ph': '84 o 084/160',
  'search.btn': 'Buscar',
  'search.manual': '✍️ Añadir a mano',
  'search.note': '💡 El <b>catálogo</b> decide en qué idioma buscas: los nombres de las cartas japonesas están en japonés (グラードン), y los de las españolas en español.<br>' +
                 'El número es el de la esquina inferior de la carta. Da igual cómo lo escribas: <b>84</b>, <b>084</b> o <b>084/160</b> valen igual.',
  'search.start': 'Escribe un nombre y pulsa <b>Buscar</b>.',
  'search.anySet': 'Cualquier expansión',
  'search.o.newest': 'Expansión más reciente',
  'search.o.priceDesc': 'Precio: de mayor a menor',
  'search.o.priceAsc': 'Precio: de menor a mayor',
  'search.o.up': 'Las que más suben (vs. mes)',
  'search.o.down': 'Las que más bajan (vs. mes)',
  'search.o.oldest': 'Expansión más antigua',
  'search.o.name': 'Nombre (A-Z)',
  'search.o.number': 'Número de carta',
  'search.inCol': 'En mi colección',
  'search.missing': 'Las que me faltan',
  'search.owned': 'Las que ya tengo',
  'search.min': 'Precio mínimo €',
  'search.min.ph': 'sin mínimo',
  'search.of': n => ' de ' + n + ' encontradas',
  'search.capped': (total, got) => ' · la búsqueda daba ' + total + ', se han traído las ' + got + ' primeras',
  'search.catalog': c => ' · catálogo ' + c,
  'search.as': w => ' · buscado como ' + w,
  'search.have': n => 'Ya tienes ' + plu(n, 'copia', 'copias'),
  'search.wishTitle': 'A la lista de deseos',
  'search.noMatch': 'Ninguna carta pasa esos filtros.',
  'search.needSome': 'Escribe al menos un nombre, una expansión o un número',
  'search.busy': 'Buscando…',
  'search.numMiss': n => 'Ninguna carta lleva el número <b>' + n + '</b> entre esos resultados, así que te muestro todas las demás: localiza la tuya por la imagen.',
  'search.none': c => 'No se han encontrado cartas en el catálogo <b>' + c + '</b>.',
  'search.noDict': name => 'En el catálogo japonés los nombres van en japonés y «' + name + '» no está en el diccionario. Busca por expansión y número, que es lo más fiable.',
  'search.tryLess': 'Prueba con menos palabras, cambia el catálogo de idioma, o añádela a mano.',
  'search.pricing': n => 'Consultando precios de ' + plu(n, 'carta', 'cartas') + '…',
  'card.notFound': 'No se encontró la carta',
  'card.loadFail': m => 'No se pudo cargar la carta: ' + m,

  /* image field */
  'img.label': 'Imagen de la carta',
  'img.useMine': '📷 Usar mi foto',
  'img.url.ph': '…o pega el enlace directo a una imagen',
  'img.remove': 'Quitar foto',
  'img.mine': 'Estás usando una foto tuya.',
  'img.hint': 'Si la carta no trae foto, hazle una o descárgala y súbela con el botón: se guarda reducida.',
  'img.page': '<b class="warn">Ese enlace es una página, no una imagen.</b> Drive y similares sirven un visor, no el archivo, y suelen pedir permiso. Descarga la foto y usa <b>📷 Usar mi foto</b>.',
  'img.notImg': 'Ese enlace no parece apuntar a una imagen (suelen acabar en .jpg o .png). Si no se ve, usa <b>📷 Usar mi foto</b>.',
  'img.looksImg': 'Enlace con pinta de imagen. Si luego no carga, ese sitio no permite enlazarla: usa <b>📷 Usar mi foto</b>.',
  'img.removed': 'Foto quitada. Al guardar, la carta se queda sin imagen.',
  'img.file': (name, type, kb) => 'Archivo: ' + name + ' · ' + type + ' · ' + kb + ' KB',
  'img.unknownType': 'tipo desconocido',
  'img.processing': 'Procesando la foto…',
  'img.readFail': '<b class="warn">No he podido leer ese archivo.</b>',
  'img.ready': (kb, label) => '✅ Foto lista (' + kb + ' KB). Se guardará al pulsar <b>' + label + '</b>.',
  'img.cantOpen': '<b class="warn">El navegador no sabe abrir ese archivo.</b> ',
  'img.heic': 'Es una foto de iPhone en formato HEIC, que Chrome no entiende: ábrela con Fotos de Windows y usa <b>Guardar como</b> → JPG.',
  'img.html': 'Es una página web guardada, no una imagen: lo que descargaste de Drive fue la página, no el archivo. En Drive, pulsa los tres puntos y elige <b>Descargar</b>.',
  'img.other': 'Prueba a abrirlo con Fotos de Windows y guardarlo como JPG o PNG.',

  /* add / edit dialog */
  'm.edit': 'Editar carta',
  'm.add': 'Añadir a mi colección',
  'm.paid': 'Precio que pagaste (€/ud)',
  'm.grade': 'Graduación (opcional)',
  'm.estValue': 'Valor estimado (€/ud)',
  'm.myPrice': 'Precio que le pongo yo (€/ud)',
  'm.youSet': 'lo pones tú',
  'm.auto.ph': 'dejar vacío = automático',
  'm.notes.ph': 'Dónde la guardas, con quién la cambiaste...',
  'm.cm': 'Buscar en Cardmarket ↗',
  'm.saveChanges': 'Guardar cambios',
  'm.prev': (u, total) => '<b>Valor estimado:</b> ' + u + ' por unidad · <b>' + total + '</b> en total',
  'm.prevMine': '(precio puesto por ti: manda sobre el automático y no se actualiza solo)',
  'm.prevCond': k => '(incluye el ajuste por estado ×' + k + ')',
  'm.saved': 'Cambios guardados',
  'm.dup': n => 'Ya la tenías: ahora tienes ' + n,
  'm.added': name => '«' + name + '» añadida a tu colección',
  'pb.manual': 'Carta añadida a mano: <b>el valor lo pones tú</b> en el campo de abajo.',
  'pb.none': 'Ninguna fuente cotiza esta carta (pasa mucho con las japonesas: existen en Cardmarket, pero el catálogo no las tiene enlazadas).<br>' +
             'Míralas con <b>Buscar en Cardmarket</b> aquí abajo y escribe el precio en <b>«Precio que le pongo yo»</b>.',
  'pb.reverse': 'Reverse (tendencia)',
  'pb.via': (src, d) => 'Cardmarket vía ' + src + ' · ' + d,

  /* manual entry */
  'x.title': 'Añadir una carta a mano',
  'x.note': 'Para lo que ninguna fuente tenga catalogado: promos raras, cartas de otros idiomas o expansiones recién salidas. Lo único imprescindible es el nombre.',
  'x.name': 'Nombre *',
  'x.set.ph': 'Nombre de la expansión',
  'x.rar.ph': 'Art Rare, SR, promo...',
  'x.notes.ph': 'Dónde la guardas, de dónde salió...',
  'x.needName': 'Ponle al menos un nombre',
  'x.added': name => '«' + name + '» añadida a mano',

  /* wishlist */
  'wish.title': 'Lista de deseos',
  'wish.sub': 'Cartas que quieres conseguir. Sus precios también se actualizan, para saber cuándo es buen momento de comprar.',
  'wish.dup': 'Ya está en tu lista de deseos',
  'wish.added': name => '«' + name + '» añadida a deseos',
  'wish.removed': 'Quitada de deseos',
  'wish.t.count': 'Cartas deseadas',
  'wish.t.pending': n => n === 1 ? 'carta pendiente' : 'cartas pendientes',
  'wish.t.cost': 'Coste estimado',
  'wish.t.today': 'Si las compraras hoy',
  'wish.empty': 'Tu lista de deseos está vacía.',
  'wish.empty2': 'Usa el botón ⭐ en los resultados de búsqueda.',
  'wish.got': '✓ La tengo',

  /* browse sets */
  'sets.title': 'Explorar una expansión completa',
  'sets.sub': 'Ideal para ir marcando las cartas que ya tienes de una expansión concreta y ver cuánto te falta para completarla.',
  'sets.load': 'Cargar expansión',
  'sets.show': 'Ver',
  'sets.have': 'Solo las que tengo',
  'sets.miss': 'Solo las que me faltan',
  'sets.pick': '— Elige una expansión —',
  'sets.start': 'Elige una expansión y pulsa <b>Cargar expansión</b>.',
  'sets.needPick': 'Elige una expansión',
  'sets.loading': 'Cargando la expansión…',
  'sets.unavailable': 'Esa expansión no está disponible en este catálogo',
  'sets.progress': (have, total) => 'Tienes ' + have + ' de ' + total + ' cartas',
  'sets.priceLater': 'El precio de cada carta se consulta al añadirla, para no lanzar cientos de peticiones de golpe.',
  'sets.inCol': 'En tu colección',
  'sets.onAdd': 'al añadir',
  'sets.nothing': 'Nada que mostrar con ese filtro.',

  /* update prices */
  'upd.progress': p => '⟳ Actualizando ' + p + '%',
  'upd.fallback': p => '⟳ Respaldo ' + p + '%',
  'upd.onlyManual': 'Solo tienes cartas añadidas a mano: esas las pones tú.',
  'upd.noCards': 'No tienes cartas registradas todavía',
  'upd.checked': n => 'Consultadas ' + plu(n, 'carta', 'cartas'),
  'upd.viaFb': n => ' (' + n + ' vía respaldo)',
  'upd.today': ' · precios de hoy',
  'upd.notYet': d => ' · Cardmarket aún no ha publicado los de hoy: estos son del ' + d,
  'upd.noPrice': n => plu(n, 'carta sin precio', 'cartas sin precio'),
  'upd.netErr': n => plu(n, 'fallo de red', 'fallos de red'),
  'tip.update': 'Consejo: pulsa «Actualizar precios» para traer los valores de hoy',

  /* statistics */
  'st.hist': 'Evolución del valor',
  'st.hist.sub': 'Se guarda una instantánea cada vez que actualizas los precios.',
  'st.top': 'Top 15 cartas más valiosas',
  'st.sets': 'Valor por expansión',
  'st.rar': 'Reparto por rareza',
  'st.src': 'De dónde sale cada precio',
  'st.src.sub': 'Cuántas cartas tuyas dependen de cada fuente.',
  'st.src.manual': 'Puesto a mano',
  'st.src.none': 'Sin precio',
  'st.t.total': 'Valor total',
  'st.t.ref': m => 'Referencia ' + m,
  'st.t.cards': 'Cartas',
  'st.t.avg': 'Valor medio por carta',
  'st.t.boughtOn': 'Sobre las cartas con precio anotado',
  'st.t.noBuy': 'Sin datos de compra',
  'st.needTwo': 'Necesitas al menos dos actualizaciones de precios en días distintos para ver la evolución.',
  'st.since': d => 'desde ' + d,
  'st.noCards': 'Sin cartas todavía.',
  'st.noData': 'Sin datos.',

  /* settings */
  'set.backup': 'Copias de seguridad',
  'set.backup.sub': 'Tu colección se guarda en este navegador. <b>Exporta un JSON de vez en cuando</b> para no perderla nunca.',
  'set.exportJson': '⬇ Exportar JSON (copia completa)',
  'set.exportCsv': '⬇ Exportar CSV (Excel)',
  'set.import': '⬆ Importar JSON',
  'set.prices': 'De dónde salen los precios',
  'set.prices.sub': 'Todos los precios son de Cardmarket y están en euros. La app usa dos fuentes para no dejarte sin cobertura.',
  'set.mode': 'Referencia de precio',
  'set.recommended': ' — recomendado',
  'set.cond': 'Ajuste por estado',
  'set.cond.on': 'Aplicar (recomendado)',
  'set.cond.off': 'No aplicar (precio base)',
  'set.cond.note': '<b>Ajuste por estado:</b> Cardmarket publica un precio de referencia general. Estos multiplicadores estiman lo que vale tu ejemplar según su conservación. Puedes cambiarlos a tu gusto.',
  'set.api': 'Clave de API (opcional)',
  'set.api.sub': 'Solo afecta a la fuente de respaldo. TCGdex no pide clave ninguna. Si ya tenías una clave de pokemontcg.io, pégala aquí para tener más margen de consultas mientras esa fuente siga viva; si no la tienes, no hace falta (ya no se pueden crear cuentas nuevas).',
  'set.api.ph': 'Pega aquí tu API key (opcional)',
  'set.danger': 'Zona peligrosa',
  'set.danger.sub': 'Esto borra toda tu colección de este navegador. Exporta una copia antes.',
  'set.wipe': '🗑 Borrar toda la colección',
  'set.credits': 'Datos de cartas y precios: <a href="https://tcgdex.dev" target="_blank" rel="noopener">TCGdex</a> y, como respaldo, <a href="https://pokemontcg.io" target="_blank" rel="noopener">pokemontcg.io</a>. ' +
                 'Los precios se originan en Cardmarket. Proyecto personal sin relación con Nintendo, The Pokémon Company ni Cardmarket. Los precios son orientativos.',
  'set.used': 'Espacio usado',
  'set.photos': n => plu(n, 'foto tuya', 'fotos tuyas'),
  'set.mb': mb => mb + ' MB de ~5 MB',
  'set.store.ok': 'Guardado automáticamente en este navegador. <b>Ojo:</b> si borras los datos de navegación o abres el archivo en otro navegador u ordenador, no verás la colección. La copia JSON es tu seguro.',
  'set.store.no': '<b class="warn">⚠ Este navegador no permite guardar datos para archivos locales.</b> Tu colección solo vivirá mientras no cierres la pestaña: exporta el JSON antes de salir e impórtalo al volver.',
  'set.src': '<b>Fuente principal: TCGdex.</b> Gratis, sin clave, con catálogo en español, inglés y japonés, y precios de Cardmarket actualizados a diario.<br>' +
             '<b>Respaldo: pokemontcg.io.</b> Solo se consulta cuando TCGdex no tiene precio de una carta, cosa que pasa en unas 90 expansiones inglesas. ',
  'set.src.eol': n => 'Esta segunda fuente se apaga el 1 de marzo de 2027 (quedan ' + n + ' días). Cuando llegue el día, las cartas que dependan de ella conservarán su último precio conocido y el resto seguirá actualizándose con normalidad.',
  'set.src.off': '<b class="warn">Esta segunda fuente ya está apagada</b>, así que las cartas que dependían de ella conservan su último precio conocido.',
  'set.modeToast': m => 'Referencia de precio: ' + m,
  'key.saved': 'Clave guardada',
  'key.removed': 'Clave eliminada',
  'exp.json': 'Copia de seguridad descargada',
  'exp.csv': 'CSV descargado (ábrelo con Excel)',
  'imp.bad': 'El archivo no tiene el formato esperado',
  'imp.confirm': n => 'Ya tienes ' + plu(n, 'entrada', 'entradas') + '.\n\nAceptar = FUSIONAR con lo importado\nCancelar = REEMPLAZAR todo por el archivo',
  'imp.done': n => 'Importadas ' + plu(n, 'entrada', 'entradas'),
  'imp.fail': m => 'No se pudo importar: ' + m,
  'wipe.c1': 'Se borrará TODA tu colección de este navegador. ¿Seguro?',
  'wipe.c2': 'Última confirmación: ¿has exportado una copia? Esto no se puede deshacer.',
  'wipe.done': 'Colección borrada'
},

en: {
  /* format */
  'locale': 'en-IE',
  'cm.lang': 'en',
  'date': (y, m, d) => new Date(Date.UTC(+y, m - 1, +d)).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'UTC' }),
  'file.base': 'pokemon-collection',
  'csv.head': ['ID','Name','Set','Number','Rarity','Variant','Condition','Language','Grade','Quantity','UnitPrice_EUR','TotalValue_EUR','PurchasePrice_EUR','Source','Updated','Notes'],
  'csv.sep': ',',
  'csv.dec': '.',
  'ui.lang': 'Interface language',

  /* header and tabs */
  'app.title': 'My Pokémon TCG Collection',
  'hdr.cards': 'cards',
  'hdr.value': 'est. value',
  'upd.btn': '⟳ Update prices',
  'tab.col': '📚 My collection',
  'tab.search': '🔍 Search & add',
  'tab.sets': '🗂️ Browse sets',
  'tab.wish': '⭐ Wishlist',
  'tab.stats': '📊 Statistics',
  'tab.settings': '⚙️ Settings',

  /* catalog, variant, price reference and table labels */
  'cats': { es: 'Español (Spanish)', en: 'English', ja: '日本語 (Japanese)' },
  'vars': { normal: 'Normal', holo: 'Holo', reverse: 'Reverse Holo', '1st': '1st Edition', promo: 'Promo' },
  'modes': { trend: 'Trend', avg: 'Average sell price', avg30: '30-day average', avg7: '7-day average', low: 'Lowest' },
  'th': { card: 'Card', set: 'Set', num: 'No.', rarity: 'Rarity', variant: 'Var.', cond: 'Cond.', lang: 'Lang.',
          qty: 'Qty', unit: 'Each', total: 'Total', paid: 'Paid', src: 'Source' },
  'lang.other': 'Other',

  /* shared bits */
  'all.f': 'All',
  'all.m': 'All',
  'clear': 'Clear',
  'add': 'Add',
  'add.btn': '+ Add',
  'cancel': 'Cancel',
  'save': 'Save',
  'retry': 'Retry',
  'optional': 'optional',
  'f.set': 'Set',
  'f.rarity': 'Rarity',
  'f.variant': 'Variant',
  'f.lang': 'Language',
  'f.price': 'Price',
  'f.catalog': 'Catalog',
  'f.sort': 'Sort by',
  'f.qty': 'Quantity',
  'f.cond': 'Condition',
  'f.number': 'Number',
  'f.notes': 'Notes',
  'no.price': 'no price',
  'unit': 'each',
  'total': 'total',
  'num.short': 'No.',
  'manual.short': 'manual',
  'manual.set': 'Added manually',
  'n.cards': n => plu(n, 'card', 'cards'),
  'n.entries': n => plu(n, 'entry', 'entries'),
  'n.sets': n => plu(n, 'set', 'sets'),
  'ago.now': 'just now',
  'ago.min': n => plu(n, 'minute', 'minutes') + ' ago',
  'ago.h': n => plu(n, 'hour', 'hours') + ' ago',
  'ago.d': n => plu(n, 'day', 'days') + ' ago',
  'tile.invested': 'Invested',
  'tile.gain': 'Gain / loss',

  /* network and storage errors */
  'err.full': 'Couldn’t save: storage is full. Export a backup.',
  'err.429': 'Too many requests in a row. Wait a minute.',
  'err.busy': s => 'The server is busy (' + s + ')',
  'err.http': s => 'Error ' + s,
  'err.offline': 'No connection',

  /* my collection */
  'col.search': 'Search my collection',
  'col.search.ph': 'Name, set, number, note...',
  'col.allSets': 'All sets',
  'price.none': '⚠ No price',
  'price.mine': 'Price set by me',
  'price.auto': 'Automatic price',
  'sort.valueDesc': 'Total value ↓',
  'sort.valueAsc': 'Total value ↑',
  'sort.unitDesc': 'Unit price ↓',
  'sort.name': 'Name A–Z',
  'sort.set': 'Set and number',
  'sort.added': 'Recently added',
  'sort.qty': 'Quantity ↓',
  'view.table': '📋 Table view',
  'view.grid': '🖼️ Grid view',
  'col.t.cards': 'Total cards',
  'col.t.distinct': n => plu(n, 'distinct entry', 'distinct entries'),
  'col.t.value': 'Estimated value',
  'col.t.ref': m => 'Reference: Cardmarket ' + m.toLowerCase(),
  'col.t.bought': 'Purchase price recorded',
  'col.t.noBuy': 'Note what you paid when adding',
  'col.t.top': 'Most expensive card',
  'col.t.unit': 'Unit price',
  'col.t.cm': 'Cardmarket prices',
  'col.t.never': 'never',
  'col.t.checked': ago => 'Checked ' + ago,
  'col.t.press': 'Press “Update prices”',
  'col.t.oldest': d => ' · oldest from ' + d,
  'col.empty': '<b>Your collection is empty.</b><br>Go to <b>Search & add</b> or <b>Browse sets</b> to record your first cards.',
  'col.noMatch': 'No results with those filters.',
  'col.showing': (n, total) => 'Showing ' + n + ' of ' + plu(total, 'entry', 'entries'),
  'col.cmTitle': 'View this card on Cardmarket',
  'col.notFound': 'Can’t find that card. Reload the page.',
  'col.notFoundRetry': 'Can’t find that card. Reload the page and try again.',
  'col.confirmDel': (name, where) => 'Remove “' + name + '” (' + where + ') from your collection?',
  'col.deleted': 'Card removed',
  'col.delFail': 'Couldn’t remove it',

  /* search and add */
  'search.title': 'Search cards',
  'search.sub': 'Search the catalog and add cards to your collection in one click.',
  'search.name': 'Card name',
  'search.name.ph': 'e.g. Charizard, Pikachu, Mew ex...',
  'search.setOpt': 'Set (optional)',
  'search.num': 'No. (optional)',
  'search.num.ph': '84 or 084/160',
  'search.btn': 'Search',
  'search.manual': '✍️ Add manually',
  'search.note': '💡 The <b>catalog</b> decides which language you search in: Japanese cards have Japanese names (グラードン), English cards English ones.<br>' +
                 'The number is the one in the card’s bottom corner. However you type it, <b>84</b>, <b>084</b> and <b>084/160</b> all work.',
  'search.start': 'Type a name and press <b>Search</b>.',
  'search.anySet': 'Any set',
  'search.o.newest': 'Newest set',
  'search.o.priceDesc': 'Price: high to low',
  'search.o.priceAsc': 'Price: low to high',
  'search.o.up': 'Biggest risers (vs. month)',
  'search.o.down': 'Biggest fallers (vs. month)',
  'search.o.oldest': 'Oldest set',
  'search.o.name': 'Name (A–Z)',
  'search.o.number': 'Card number',
  'search.inCol': 'In my collection',
  'search.missing': 'Ones I’m missing',
  'search.owned': 'Ones I have',
  'search.min': 'Minimum price €',
  'search.min.ph': 'no minimum',
  'search.of': n => ' of ' + n + ' found',
  'search.capped': (total, got) => ' · the search matched ' + total + '; showing the first ' + got,
  'search.catalog': c => ' · ' + c + ' catalog',
  'search.as': w => ' · searched as ' + w,
  'search.have': n => 'You have ' + plu(n, 'copy', 'copies'),
  'search.wishTitle': 'Add to wishlist',
  'search.noMatch': 'No cards match those filters.',
  'search.needSome': 'Enter at least a name, a set or a number',
  'search.busy': 'Searching…',
  'search.numMiss': n => 'None of those results has number <b>' + n + '</b>, so here are all the others: spot yours by its picture.',
  'search.none': c => 'No cards found in the <b>' + c + '</b> catalog.',
  'search.noDict': name => 'In the Japanese catalog names are in Japanese, and “' + name + '” isn’t in the dictionary. Search by set and number instead, which is the most reliable way.',
  'search.tryLess': 'Try fewer words, switch the catalog language, or add it manually.',
  'search.pricing': n => 'Fetching prices for ' + plu(n, 'card', 'cards') + '…',
  'card.notFound': 'Card not found',
  'card.loadFail': m => 'Couldn’t load the card: ' + m,

  /* image field */
  'img.label': 'Card image',
  'img.useMine': '📷 Use my photo',
  'img.url.ph': '…or paste a direct link to an image',
  'img.remove': 'Remove photo',
  'img.mine': 'You’re using your own photo.',
  'img.hint': 'If the card has no picture, take a photo or download one and upload it with the button: it’s stored downsized.',
  'img.page': '<b class="warn">That link is a page, not an image.</b> Drive and similar sites serve a viewer, not the file, and often ask for permission. Download the photo and use <b>📷 Use my photo</b>.',
  'img.notImg': 'That link doesn’t look like an image (those usually end in .jpg or .png). If it doesn’t show, use <b>📷 Use my photo</b>.',
  'img.looksImg': 'Looks like an image link. If it doesn’t load later, that site doesn’t allow linking to it: use <b>📷 Use my photo</b>.',
  'img.removed': 'Photo removed. When you save, the card will have no image.',
  'img.file': (name, type, kb) => 'File: ' + name + ' · ' + type + ' · ' + kb + ' KB',
  'img.unknownType': 'unknown type',
  'img.processing': 'Processing the photo…',
  'img.readFail': '<b class="warn">I couldn’t read that file.</b>',
  'img.ready': (kb, label) => '✅ Photo ready (' + kb + ' KB). It will be saved when you press <b>' + label + '</b>.',
  'img.cantOpen': '<b class="warn">The browser can’t open that file.</b> ',
  'img.heic': 'It’s an iPhone photo in HEIC format, which Chrome can’t read: open it in Windows Photos and use <b>Save as</b> → JPG.',
  'img.html': 'It’s a saved web page, not an image: what you downloaded from Drive was the page, not the file. In Drive, click the three dots and choose <b>Download</b>.',
  'img.other': 'Try opening it in Windows Photos and saving it as JPG or PNG.',

  /* add / edit dialog */
  'm.edit': 'Edit card',
  'm.add': 'Add to my collection',
  'm.paid': 'Price you paid (€ each)',
  'm.grade': 'Grade (optional)',
  'm.estValue': 'Estimated value (€ each)',
  'm.myPrice': 'My own price (€ each)',
  'm.youSet': 'you set it',
  'm.auto.ph': 'leave empty = automatic',
  'm.notes.ph': 'Where you keep it, who you traded it with...',
  'm.cm': 'Search on Cardmarket ↗',
  'm.saveChanges': 'Save changes',
  'm.prev': (u, total) => '<b>Estimated value:</b> ' + u + ' each · <b>' + total + '</b> in total',
  'm.prevMine': '(price set by you: it overrides the automatic one and doesn’t update by itself)',
  'm.prevCond': k => '(includes the condition adjustment ×' + k + ')',
  'm.saved': 'Changes saved',
  'm.dup': n => 'You already had it: now you have ' + n,
  'm.added': name => '“' + name + '” added to your collection',
  'pb.manual': 'Card added manually: <b>you set its value</b> in the field below.',
  'pb.none': 'No source has a price for this card (common with Japanese cards: they exist on Cardmarket, but the catalog doesn’t link them).<br>' +
             'Look it up with <b>Search on Cardmarket</b> below and type the price into <b>“My own price”</b>.',
  'pb.reverse': 'Reverse (trend)',
  'pb.via': (src, d) => 'Cardmarket via ' + src + ' · ' + d,

  /* manual entry */
  'x.title': 'Add a card manually',
  'x.note': 'For anything no source has catalogued: rare promos, cards in other languages or brand-new sets. Only the name is required.',
  'x.name': 'Name *',
  'x.set.ph': 'Set name',
  'x.rar.ph': 'Art Rare, SR, promo...',
  'x.notes.ph': 'Where you keep it, where it came from...',
  'x.needName': 'Give it at least a name',
  'x.added': name => '“' + name + '” added manually',

  /* wishlist */
  'wish.title': 'Wishlist',
  'wish.sub': 'Cards you want to get. Their prices update too, so you can tell when it’s a good time to buy.',
  'wish.dup': 'It’s already on your wishlist',
  'wish.added': name => '“' + name + '” added to your wishlist',
  'wish.removed': 'Removed from wishlist',
  'wish.t.count': 'Wanted cards',
  'wish.t.pending': n => n === 1 ? 'card to get' : 'cards to get',
  'wish.t.cost': 'Estimated cost',
  'wish.t.today': 'If you bought them today',
  'wish.empty': 'Your wishlist is empty.',
  'wish.empty2': 'Use the ⭐ button in the search results.',
  'wish.got': '✓ Got it',

  /* browse sets */
  'sets.title': 'Browse a whole set',
  'sets.sub': 'Handy for ticking off the cards you already own from a set and seeing how many you’re missing to complete it.',
  'sets.load': 'Load set',
  'sets.show': 'Show',
  'sets.have': 'Only the ones I have',
  'sets.miss': 'Only the ones I’m missing',
  'sets.pick': '— Pick a set —',
  'sets.start': 'Pick a set and press <b>Load set</b>.',
  'sets.needPick': 'Pick a set',
  'sets.loading': 'Loading the set…',
  'sets.unavailable': 'That set isn’t available in this catalog',
  'sets.progress': (have, total) => 'You have ' + have + ' of ' + total + ' cards',
  'sets.priceLater': 'Each card’s price is fetched when you add it, so as not to fire off hundreds of requests at once.',
  'sets.inCol': 'In your collection',
  'sets.onAdd': 'when added',
  'sets.nothing': 'Nothing to show with that filter.',

  /* update prices */
  'upd.progress': p => '⟳ Updating ' + p + '%',
  'upd.fallback': p => '⟳ Fallback ' + p + '%',
  'upd.onlyManual': 'You only have manually added cards: you set those prices yourself.',
  'upd.noCards': 'You haven’t recorded any cards yet',
  'upd.checked': n => 'Checked ' + plu(n, 'card', 'cards'),
  'upd.viaFb': n => ' (' + n + ' via fallback)',
  'upd.today': ' · today’s prices',
  'upd.notYet': d => ' · Cardmarket hasn’t published today’s yet: these are from ' + d,
  'upd.noPrice': n => plu(n, 'card without a price', 'cards without a price'),
  'upd.netErr': n => plu(n, 'network error', 'network errors'),
  'tip.update': 'Tip: press “Update prices” to get today’s values',

  /* statistics */
  'st.hist': 'Value over time',
  'st.hist.sub': 'A snapshot is saved every time you update prices.',
  'st.top': 'Top 15 most valuable cards',
  'st.sets': 'Value by set',
  'st.rar': 'Cards by rarity',
  'st.src': 'Where each price comes from',
  'st.src.sub': 'How many of your cards rely on each source.',
  'st.src.manual': 'Set manually',
  'st.src.none': 'No price',
  'st.t.total': 'Total value',
  'st.t.ref': m => 'Reference: ' + m.toLowerCase(),
  'st.t.cards': 'Cards',
  'st.t.avg': 'Average value per card',
  'st.t.boughtOn': 'On cards with a recorded purchase price',
  'st.t.noBuy': 'No purchase data',
  'st.needTwo': 'You need at least two price updates on different days to see the trend.',
  'st.since': d => 'since ' + d,
  'st.noCards': 'No cards yet.',
  'st.noData': 'No data.',

  /* settings */
  'set.backup': 'Backups',
  'set.backup.sub': 'Your collection is stored in this browser. <b>Export a JSON now and then</b> so you never lose it.',
  'set.exportJson': '⬇ Export JSON (full backup)',
  'set.exportCsv': '⬇ Export CSV (Excel)',
  'set.import': '⬆ Import JSON',
  'set.prices': 'Where prices come from',
  'set.prices.sub': 'All prices come from Cardmarket and are in euros. The app uses two sources so you’re never left without coverage.',
  'set.mode': 'Price reference',
  'set.recommended': ' — recommended',
  'set.cond': 'Condition adjustment',
  'set.cond.on': 'Apply (recommended)',
  'set.cond.off': 'Don’t apply (base price)',
  'set.cond.note': '<b>Condition adjustment:</b> Cardmarket publishes one general reference price. These multipliers estimate what your copy is worth given its condition. Change them as you like.',
  'set.api': 'API key (optional)',
  'set.api.sub': 'Only affects the fallback source. TCGdex needs no key at all. If you already had a pokemontcg.io key, paste it here for a higher request allowance while that source is still alive; if you don’t have one, you don’t need it (new accounts can no longer be created).',
  'set.api.ph': 'Paste your API key here (optional)',
  'set.danger': 'Danger zone',
  'set.danger.sub': 'This deletes your whole collection from this browser. Export a backup first.',
  'set.wipe': '🗑 Delete the whole collection',
  'set.credits': 'Card and price data: <a href="https://tcgdex.dev" target="_blank" rel="noopener">TCGdex</a> and, as a fallback, <a href="https://pokemontcg.io" target="_blank" rel="noopener">pokemontcg.io</a>. ' +
                 'Prices originate from Cardmarket. A personal project not affiliated with Nintendo, The Pokémon Company or Cardmarket. Prices are indicative.',
  'set.used': 'Storage used',
  'set.photos': n => plu(n, 'own photo', 'own photos'),
  'set.mb': mb => mb + ' MB of ~5 MB',
  'set.store.ok': 'Saved automatically in this browser. <b>Note:</b> if you clear your browsing data or open the file in another browser or computer, you won’t see the collection. The JSON backup is your safety net.',
  'set.store.no': '<b class="warn">⚠ This browser doesn’t allow saving data for local files.</b> Your collection only lasts until you close the tab: export the JSON before leaving and import it when you come back.',
  'set.src': '<b>Main source: TCGdex.</b> Free, no key, with a Spanish, English and Japanese catalog and Cardmarket prices updated daily.<br>' +
             '<b>Fallback: pokemontcg.io.</b> Only used when TCGdex has no price for a card, which happens in about 90 English sets. ',
  'set.src.eol': n => 'This second source shuts down on 1 March 2027 (' + n + ' days left). When that day comes, cards that rely on it keep their last known price and everything else keeps updating as normal.',
  'set.src.off': '<b class="warn">This second source has already shut down</b>, so cards that relied on it keep their last known price.',
  'set.modeToast': m => 'Price reference: ' + m,
  'key.saved': 'Key saved',
  'key.removed': 'Key removed',
  'exp.json': 'Backup downloaded',
  'exp.csv': 'CSV downloaded (open it with Excel)',
  'imp.bad': 'The file isn’t in the expected format',
  'imp.confirm': n => 'You already have ' + plu(n, 'entry', 'entries') + '.\n\nOK = MERGE with the imported file\nCancel = REPLACE everything with the file',
  'imp.done': n => 'Imported ' + plu(n, 'entry', 'entries'),
  'imp.fail': m => 'Import failed: ' + m,
  'wipe.c1': 'This will delete your WHOLE collection from this browser. Are you sure?',
  'wipe.c2': 'Last confirmation: have you exported a backup? This can’t be undone.',
  'wipe.done': 'Collection deleted'
}

};
